<section class = "main-section content" id = "myStory">
        <h2><?php echo __("My Story"); ?></h2>
        <p><?php echo __("Hi there! I am Pan Chen. It is also my Chinese name. If you are curious how to pronounce my name correctly, it is \"Panda\" without \"-da\" in the end."); ?></p>
        <p><?php echo __("I was born and grew up in a coastal city in southeastern China. I have a family of four, and I am the only one in my family who studies computer science, or even computer science related stuff."); ?></p>
        <p><?php echo __("I was a lousy student until Grade 8 when I transformed myself into a good student. I don't know why I decided to make such a change and locked my PSP and PS Vita in the safe at that time. But thanks to that year's hard-working, I was able to continue my studies at the best high school in the province, and this is what I feel proudest of even today. Ever since then, I believe that the harder you work, the luckier you are."); ?></p>
        <p><?php echo __("After leaving high school, I moved to the north part of China to attend university. I saw the snow for the first time during my stay there. I chose computer engineering as my program, and this is how I became the only one in my family."); ?></p>
        <p><?php echo __("Then, I moved to Canada to continue my studies at a research-based University. Since I was a transfer student, I faced the risk of losing the chance to study what I am passionate about, due to the capacity limit of the computer science program. But again, I worked hard, and I gained the chance. Now, I study not only computer science but also statistics science. I hope that I can utilize the power of big data to do something good."); ?></p>
        <p><?php echo __("This year, I am doing an internship as a software developer. Though my goal is going to graduate school after my four-year undergraduate study, I still believe that one year in the industry is valuable to me as I can better understand how to collaborate with my team. I will be more efficient and responsible because I need to keep my commitments with high quality on time. I get the salary, so I have to make my efforts."); ?></p>
        <p><?php echo __("Besides, I also join a research program offered by my university. Internship and research at the same time are challenging stuff. But I am sure after this year, I will learn a lot, and this's all my hard-working is worth for."); ?></p>
        <p><?php echo __("My motto is \"Take the public interests into account, Seek the popular honour with immortality\". It sounds big, but if speaking in a more easy-to-understand way, I always try to give others my hands if I can."); ?></p>
        <p><?php echo __("Also, I own a wide range of interests, from music, movies to history, politics and so on. During my spare time, I work on my debut novel, a book based on my real high school life."); ?></p>
</section>